spring:
  datasource:
      url: jdbc:mysql://localhost:3306/chaosquark_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: mysql
      driver-class-name: com.mysql.jdbc.Driver
      platform: mysql
      type: com.alibaba.druid.pool.DruidDataSource
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initialSize: 1
      minIdle: 3
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      #useGlobalDataSourceStat: true

  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: create

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.chaosquark.backend.entity
  type-handlers-package: com.chaosquark.backend.common.mybatis.handler

mapper:
  mappers: com.chaosquark.backend.common.tkmapper.MyTkMapper
  identity: MYSQL

shiro:
  hashAlgorithmName: md5
  hashIterations: 3
